export COLOR_NORMAL="[0m"

export COLOR_BLACK="[0;30m"
export COLOR_RED="[0;31m"
export COLOR_GREEN="[0;32m"
export COLOR_YELLOW="[0;33m"
export COLOR_BLUE="[0;34m"
export COLOR_MAGENTA="[0;35m"
export COLOR_CYAN="[0;36m"
export COLOR_WHITE="[0;37m"

export COLOR_BOLD_BLACK="[1;30m"
export COLOR_BOLD_RED="[1;31m"
export COLOR_BOLD_GREEN="[1;32m"
export COLOR_BOLD_YELLOW="[1;33m"
export COLOR_BOLD_BLUE="[1;34m"
export COLOR_BOLD_MAGENTA="[1;35m"
export COLOR_BOLD_CYAN="[1;36m"
export COLOR_BOLD_WHITE="[1;37m"
