bindkey "[H" beginning-of-line
bindkey "[F" end-of-line
bindkey "[1;5A" beginning-of-line
bindkey "[1;5B" end-of-line
bindkey "[1;5D" backward-word
bindkey "[1;5C" forward-word
bindkey "" backward-kill-word
bindkey "[3;5~" kill-word
